Upgrade Storybook to v6
theforeman/foreman-js pull request #214
Opened 2020-09-02 19:03 UTC by jeremylenz

2020-09-28 20:04 UTC, jeremylenz commented on packages/stories/src/index.js
> -export * from '@storybook/addon-storysource';
Storybook didn't render when both of these were exported.  Probably not safe to `export * from` multiple npm packages when some of the exports could have the same names.

2020-09-29 19:02 UTC, jeremylenz commented
@sharvit @johnpmitsch rebased and ready for review :)

Will squash once acked

2020-09-29 19:57 UTC, jeremylenz commented on packages/stories/src/config/services/sorting.js
> +  if (combined) {
will evaluate to false if `0`

2020-09-29 19:59 UTC, jeremylenz commented on packages/stories/src/config/webpack/webpack.config.vendor.js
> +    p => p.constructor.name === 'HtmlWebpackPlugin'
After the upgrade it appears the order of `config.plugins` changed, so I changed this to look for the correct name instead

2020-10-01 15:17 UTC, johnpmitsch commented
The functionality appears to be working great! 

The code seems fine but I need to take a closer look at the webpack aspect of it as I'm not as familiar with the existing code there. Maybe @sharvit can review that part better.

2020-11-06 22:03 UTC, jeremylenz commented
@sharvit can this be merged soon?

2020-11-13 11:57 UTC, johnpmitsch commented
@jeremylenz commits look a little funky here, did something happen when rebasing?

2020-11-13 17:53 UTC, jeremylenz commented
@johnpmitsch Re-rebased, hopefully it's better now

2020-11-13 19:33 UTC, johnpmitsch commented
@jeremylenz still working well :+1:

2020-11-13 19:34 UTC, johnpmitsch approved these changes

2020-11-16 08:04 UTC, sharvit requested changes
Thanks @jeremylenz 👍 

I deployed those changes to `npm` as `6.1.0-next-storybook-6-upgrade.0` and it works well together with https://github.com/theforeman/foreman/pull/7990, see:
- https://github.com/theforeman/foreman-js/releases/tag/v6.1.0-next-storybook-6-upgrade.0

To install it, replace the version in the `package.json` with `^6.1.0-next-storybook-6-upgrade.0`.

1. Please update the readme file according to the changes and the deprecations.

2. Please squash and finalize your commit message.
In your commit, describe the breaking changes and write a migration guide so it will be landed in the changelog (https://github.com/theforeman/foreman-js/blob/master/CHANGELOG.md) and in the release notes (https://github.com/theforeman/foreman-js/releases).

2020-11-16 13:41 UTC, jeremylenz commented on packages/stories/src/config/decorators/centered.js
> -export const centered = (...args) => {
Correct, see https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-addon-centered

2020-11-16 18:28 UTC, jeremylenz commented
Thanks @sharvit, squashed and updated!

2020-11-17 09:30 UTC, sharvit commented
Thanks @jeremylenz 

1. Please add another depreciation error and a breaking change line about the `storiesOf` is not supported anymore.

2. I was playing with the changelog and the release notes generator and it seems to be working best when I formated the commit as well:
```
    feat(stories): update Storybook to v6

    BREAKING CHANGE: @storybook/addon-knobs, @storybook/addon-actions,
    and @storybook/addon-storysource are no longer re-exported
    from @theforeman/stories.  Going forward, import these items
    directly: e.g. `import { withKnobs } from @storybook/addon-knobs`
    instead of `import { withKnobs } from @theforeman/stories`.
    Deprecation error messages have been added where appropriate.

    BREAKING CHANGE: The Preview component has been renamed to Canvas.

    BREAKING CHANGE: The Props component has been renamed to ArgsTable.

    BREAKING CHANGE: Custom separators are no longer supported in story titles.
    Instead of `title: 'Components|DiffView'` you must write `title: 'Components/DiffView'`.
```

This format generated the following release notes:
- https://github.com/theforeman/foreman-js/releases/tag/v7.0.0-next-storybook-v6.0
- https://github.com/theforeman/foreman-js/blob/v7.0.0-next-storybook-v6.0/CHANGELOG.md#700-next-storybook-v60-2020-11-17

Please format the commit accordingly.

2020-11-17 15:20 UTC, jeremylenz commented
@sharvit updated and formatted the commit message!

2020-11-18 12:37 UTC, sharvit approved these changes
Thanks @jeremylenz

2020-11-18 12:38 UTC, merged

2020-11-18 14:54 UTC, sharvit commented
Published as v7.0.0, see https://github.com/theforeman/foreman-js/releases/tag/v7.0.0